name: "Newt - Pangolin Tunnels"
description: "Secure remote access with Pangolin tunnels."
maintainer: Alex Moras <alex@codesix.net>
url: https://docs.fossorial.io
version: "0.6.0"
slug: "newt"
image: "ghcr.io/alexmoras/image-{arch}-hass-addon-newt"
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
hassio_api: true
docker_api: true
options:
  id: null
  secret: null
  endpoint: null
  dns:
  log-level: "INFO"
  tls-client-cert:
  docker: false
schema:
  id: str
  secret: str
  endpoint: str
  dns: str?
  log-level: list(DEBUG|INFO|NOTICE|WARN|ERROR)
  tls-client-cert: str?
  docker: bool